name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 14

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn generate

  test:
    name: Unit Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Test
        run: yarn test --ci
      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v3.1.0
