name: Node CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js 12
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 12
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --ci
      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v2.0.2
