name: Production

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js 12
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: BASE_PATH=/${GITHUB_REPOSITORY##*/} yarn generate

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dist
          path: |
            dist
            !dist/**.md

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: dist
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: 'ci: auto deployment from'
