name: Release

on:
  push:
    tags:
      - v*
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js 12
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: Get yarn cache directory path
        id: yarn-config
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.yarn-config.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Production Build
        run: |
          BASE_PATH=/${GITHUB_REPOSITORY##*/} yarn generate
          rm dist/README.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: 'ci: auto deployment from'
