name: Release

on:
  push:
    tags:
      - v*
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js 12
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Production Build
        run: |
          BASE_PATH=/${GITHUB_REPOSITORY##*/} yarn generate
          rm dist/README.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: 'ci: auto deployment from'
